steps:
# 1. Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-project-455402/my-repo/gke-app:$SHORT_SHA', '.']

# 2. Push to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gcp-project-455402/my-repo/gke-app:$SHORT_SHA']

# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['set', 'image', 'deployment/app', 'app=us-central1-docker.pkg.dev/gcp-project-455402/my-repo/gke-app:$SHORT_SHA']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'

# 3. Replace Image Tag in Deployment File
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      sed -i 's|us-central1-docker.pkg.dev/gcp-project-455402/my-repo/gke-app:latest|us-central1-docker.pkg.dev/gcp-project-455402/my-repo/gke-app:$SHORT_SHA|' k8s/deployment.yaml

# 4. Deploy to GKE using `kubectl apply`
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'k8s/deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-cluster'

# options:
#   logging: CLOUD_LOGGING_ONLY  
